/**
 * Error code registry for the Scheduling bounded context.
 *
 * Namespaced with `SCHEDULING.` prefix to avoid collisions with core ErrorCodes
 * and codes from other bounded contexts (ADR-0012).
 */
export const SchedulingErrorCodes = {
  INVALID_BOOKING_TRANSITION: 'SCHEDULING.INVALID_BOOKING_TRANSITION',
  INVALID_DURATION: 'SCHEDULING.INVALID_DURATION',
  INVALID_TIME_SLOT: 'SCHEDULING.INVALID_TIME_SLOT',
  OVERLAPPING_TIME_SLOT: 'SCHEDULING.OVERLAPPING_TIME_SLOT',
  INVALID_SESSION_TITLE: 'SCHEDULING.INVALID_SESSION_TITLE',
  SESSION_NOT_FOUND: 'SCHEDULING.SESSION_NOT_FOUND',
  SESSION_NOT_ACTIVE: 'SCHEDULING.SESSION_NOT_ACTIVE',
  BOOKING_NOT_FOUND: 'SCHEDULING.BOOKING_NOT_FOUND',
  WORKING_AVAILABILITY_NOT_FOUND: 'SCHEDULING.WORKING_AVAILABILITY_NOT_FOUND',
  RECURRING_SCHEDULE_NOT_FOUND: 'SCHEDULING.RECURRING_SCHEDULE_NOT_FOUND',
  DOUBLE_BOOKING: 'SCHEDULING.DOUBLE_BOOKING',
  OPERATIONAL_LIMIT_EXCEEDED: 'SCHEDULING.OPERATIONAL_LIMIT_EXCEEDED',
  PROFESSIONAL_BANNED: 'SCHEDULING.PROFESSIONAL_BANNED',
  RECURRING_SESSION_LIMIT_EXCEEDED: 'SCHEDULING.RECURRING_SESSION_LIMIT_EXCEEDED',
  INVALID_RECURRENCE_COUNT: 'SCHEDULING.INVALID_RECURRENCE_COUNT',
  SLOT_OUTSIDE_AVAILABILITY: 'SCHEDULING.SLOT_OUTSIDE_AVAILABILITY',
  ACCESS_GRANT_INVALID: 'SCHEDULING.ACCESS_GRANT_INVALID',
} as const;

export type SchedulingErrorCode = (typeof SchedulingErrorCodes)[keyof typeof SchedulingErrorCodes];
