/**
 * Canonical error code registry for the Goals bounded context.
 *
 * Module-scoped codes follow the DOMAIN.CODE pattern to avoid collisions
 * with other bounded contexts.
 */
export const GoalsErrorCodes = {
  INVALID_GOAL_ID: 'GOALS.INVALID_GOAL_ID',
  INVALID_GOAL_CATEGORY: 'GOALS.INVALID_GOAL_CATEGORY',
  INVALID_GOAL_METRIC: 'GOALS.INVALID_GOAL_METRIC',
  INVALID_GOAL_NAME: 'GOALS.INVALID_GOAL_NAME',
  INVALID_GOAL_PRIORITY: 'GOALS.INVALID_GOAL_PRIORITY',
  INVALID_PROGRESS_SOURCE: 'GOALS.INVALID_PROGRESS_SOURCE',
  INVALID_PROGRESS_PERCENTAGE: 'GOALS.INVALID_PROGRESS_PERCENTAGE',
  INVALID_TARGET_DATE: 'GOALS.INVALID_TARGET_DATE',
  INVALID_BASELINE_VALUE: 'GOALS.INVALID_BASELINE_VALUE',
  INVALID_TARGET_VALUE: 'GOALS.INVALID_TARGET_VALUE',
  INVALID_CURRENT_VALUE: 'GOALS.INVALID_CURRENT_VALUE',
  INVALID_MILESTONE_NAME: 'GOALS.INVALID_MILESTONE_NAME',
  BASELINE_GREATER_THAN_TARGET: 'GOALS.BASELINE_GREATER_THAN_TARGET',
  GOAL_NOT_FOUND: 'GOALS.GOAL_NOT_FOUND',
  GOAL_ALREADY_APPROVED: 'GOALS.GOAL_ALREADY_APPROVED',
  GOAL_ALREADY_STARTED: 'GOALS.GOAL_ALREADY_STARTED',
  GOAL_NOT_APPROVED: 'GOALS.GOAL_NOT_APPROVED',
  GOAL_NOT_ACTIVE: 'GOALS.GOAL_NOT_ACTIVE',
  GOAL_ALREADY_COMPLETED: 'GOALS.GOAL_ALREADY_COMPLETED',
  INVALID_PROFESSIONAL_ID: 'GOALS.INVALID_PROFESSIONAL_ID',
  INVALID_CLIENT_ID: 'GOALS.INVALID_CLIENT_ID',
  UNAUTHORIZED_PROFESSIONAL: 'GOALS.UNAUTHORIZED_PROFESSIONAL',
  INVALID_MILESTONE_TARGET: 'GOALS.INVALID_MILESTONE_TARGET',
} as const;

export type GoalsErrorCode = (typeof GoalsErrorCodes)[keyof typeof GoalsErrorCodes];
