/**
 * Error code registry for the Achievements bounded context.
 *
 * Namespaced with `ACHIEVEMENT.` prefix to avoid collisions with
 * core ErrorCodes and codes from other bounded contexts.
 */
export const AchievementErrorCodes = {
  INVALID_ACHIEVEMENT_CODE: 'ACHIEVEMENT.INVALID_ACHIEVEMENT_CODE',
  INVALID_CRITERIA: 'ACHIEVEMENT.INVALID_CRITERIA',
  ACHIEVEMENT_ALREADY_UNLOCKED: 'ACHIEVEMENT.ACHIEVEMENT_ALREADY_UNLOCKED',
  INVALID_PROGRESS_VALUE: 'ACHIEVEMENT.INVALID_PROGRESS_VALUE',
  INVALID_METRIC_TYPE: 'ACHIEVEMENT.INVALID_METRIC_TYPE',
  INVALID_OPERATOR: 'ACHIEVEMENT.INVALID_OPERATOR',
  ACHIEVEMENT_DEFINITION_NOT_FOUND: 'ACHIEVEMENT.ACHIEVEMENT_DEFINITION_NOT_FOUND',
  ACHIEVEMENT_DEFINITION_ALREADY_ACTIVE: 'ACHIEVEMENT.ACHIEVEMENT_DEFINITION_ALREADY_ACTIVE',
  ACHIEVEMENT_CODE_ALREADY_EXISTS: 'ACHIEVEMENT.ACHIEVEMENT_CODE_ALREADY_EXISTS',
  INVALID_ACHIEVEMENT_DEFINITION: 'ACHIEVEMENT.INVALID_ACHIEVEMENT_DEFINITION',
} as const;

export type AchievementErrorCode =
  (typeof AchievementErrorCodes)[keyof typeof AchievementErrorCodes];
