/**
 * Booking lifecycle status per ADR-0008.
 *
 * Valid transitions:
 * ```
 * PENDING → CONFIRMED
 * PENDING → CANCELLED_BY_CLIENT
 * PENDING → CANCELLED_BY_PROFESSIONAL
 * CONFIRMED → CANCELLED_BY_CLIENT
 * CONFIRMED → CANCELLED_BY_PROFESSIONAL
 * CONFIRMED → CANCELLED_BY_SYSTEM
 * CONFIRMED → COMPLETED
 * CONFIRMED → NO_SHOW
 * ```
 *
 * Terminal states: CANCELLED_BY_CLIENT, CANCELLED_BY_PROFESSIONAL,
 * CANCELLED_BY_SYSTEM, COMPLETED, NO_SHOW.
 */
export enum BookingStatus {
  PENDING = 'PENDING',
  CONFIRMED = 'CONFIRMED',
  CANCELLED_BY_CLIENT = 'CANCELLED_BY_CLIENT',
  CANCELLED_BY_PROFESSIONAL = 'CANCELLED_BY_PROFESSIONAL',
  CANCELLED_BY_SYSTEM = 'CANCELLED_BY_SYSTEM',
  COMPLETED = 'COMPLETED',
  NO_SHOW = 'NO_SHOW',
}
