/**
 * Error code registry for the SessionFeedback bounded context.
 *
 * Namespaced with `SESSION_FEEDBACK.` prefix to avoid collisions with
 * core ErrorCodes and codes from other bounded contexts.
 */
export const SessionFeedbackErrorCodes = {
  INVALID_FEEDBACK: 'SESSION_FEEDBACK.INVALID_FEEDBACK',
  FEEDBACK_NOT_FOUND: 'SESSION_FEEDBACK.FEEDBACK_NOT_FOUND',
  INVALID_RATING: 'SESSION_FEEDBACK.INVALID_RATING',
  INVALID_COMMENT: 'SESSION_FEEDBACK.INVALID_COMMENT',
  FEEDBACK_WINDOW_CLOSED: 'SESSION_FEEDBACK.FEEDBACK_WINDOW_CLOSED',
  FEEDBACK_ALREADY_EXISTS: 'SESSION_FEEDBACK.FEEDBACK_ALREADY_EXISTS',
  FEEDBACK_ALREADY_FLAGGED: 'SESSION_FEEDBACK.FEEDBACK_ALREADY_FLAGGED',
  FEEDBACK_ALREADY_HIDDEN: 'SESSION_FEEDBACK.FEEDBACK_ALREADY_HIDDEN',
  NOT_BOOKING_CLIENT: 'SESSION_FEEDBACK.NOT_BOOKING_CLIENT',
  BOOKING_NOT_COMPLETED: 'SESSION_FEEDBACK.BOOKING_NOT_COMPLETED',
  UNAUTHORIZED_ACTION: 'SESSION_FEEDBACK.UNAUTHORIZED_ACTION',
} as const;

export type SessionFeedbackErrorCode =
  (typeof SessionFeedbackErrorCodes)[keyof typeof SessionFeedbackErrorCodes];
