/**
 * Error code registry for the Billing bounded context.
 *
 * Namespaced with `BILLING.` prefix to avoid collisions with core ErrorCodes
 * and codes from other bounded contexts.
 */
export const BillingErrorCodes = {
  INVALID_SERVICE_PLAN: 'BILLING.INVALID_SERVICE_PLAN',
  INVALID_SERVICE_PLAN_TRANSITION: 'BILLING.INVALID_SERVICE_PLAN_TRANSITION',
  INVALID_TRANSACTION_TRANSITION: 'BILLING.INVALID_TRANSACTION_TRANSITION',
  INVALID_ACCESS_GRANT_TRANSITION: 'BILLING.INVALID_ACCESS_GRANT_TRANSITION',
  INVALID_PLATFORM_FEE: 'BILLING.INVALID_PLATFORM_FEE',
  SERVICE_PLAN_NOT_FOUND: 'BILLING.SERVICE_PLAN_NOT_FOUND',
  SERVICE_PLAN_NOT_ACTIVE: 'BILLING.SERVICE_PLAN_NOT_ACTIVE',
  TRANSACTION_NOT_FOUND: 'BILLING.TRANSACTION_NOT_FOUND',
  TRANSACTION_NOT_CONFIRMED: 'BILLING.TRANSACTION_NOT_CONFIRMED',
  ACCESS_GRANT_NOT_FOUND: 'BILLING.ACCESS_GRANT_NOT_FOUND',
} as const;

export type BillingErrorCode = (typeof BillingErrorCodes)[keyof typeof BillingErrorCodes];
