/**
 * Canonical error code registry for the Challenges bounded context.
 *
 * Module-scoped codes follow the DOMAIN.CODE pattern to avoid collisions
 * with other bounded contexts.
 */
export const ChallengeErrorCodes = {
  INVALID_CHALLENGE_ID: 'CHALLENGES.INVALID_CHALLENGE_ID',
  INVALID_CHALLENGE_TYPE: 'CHALLENGES.INVALID_CHALLENGE_TYPE',
  INVALID_GOAL_TARGET: 'CHALLENGES.INVALID_GOAL_TARGET',
  INVALID_METRIC_TYPE: 'CHALLENGES.INVALID_METRIC_TYPE',
  INVALID_CHALLENGE_NAME: 'CHALLENGES.INVALID_CHALLENGE_NAME',
  INVALID_CHALLENGE_DESCRIPTION: 'CHALLENGES.INVALID_CHALLENGE_DESCRIPTION',
  INVALID_VISIBILITY: 'CHALLENGES.INVALID_VISIBILITY',
  INVALID_CATEGORY: 'CHALLENGES.INVALID_CATEGORY',
  INVALID_REWARD_POLICY: 'CHALLENGES.INVALID_REWARD_POLICY',
  INVALID_PARTICIPANTS_COUNT: 'CHALLENGES.INVALID_PARTICIPANTS_COUNT',
  INVALID_PROGRESS: 'CHALLENGES.INVALID_PROGRESS',
  INVALID_PROGRESS_PERCENTAGE: 'CHALLENGES.INVALID_PROGRESS_PERCENTAGE',
  INVALID_DURATION: 'CHALLENGES.INVALID_DURATION',
  CHALLENGE_NOT_JOINABLE: 'CHALLENGES.CHALLENGE_NOT_JOINABLE',
  ALREADY_JOINED_CHALLENGE: 'CHALLENGES.ALREADY_JOINED_CHALLENGE',
  CHALLENGE_FULL: 'CHALLENGES.CHALLENGE_FULL',
  NOT_PARTICIPANT: 'CHALLENGES.NOT_PARTICIPANT',
  CHALLENGE_NOT_ACTIVE: 'CHALLENGES.CHALLENGE_NOT_ACTIVE',
  CHALLENGE_NOT_ENDED: 'CHALLENGES.CHALLENGE_NOT_ENDED',
  CHALLENGE_ALREADY_STARTED: 'CHALLENGES.CHALLENGE_ALREADY_STARTED',
  CHALLENGE_ALREADY_ENDED: 'CHALLENGES.CHALLENGE_ALREADY_ENDED',
  CHALLENGE_ALREADY_CANCELED: 'CHALLENGES.CHALLENGE_ALREADY_CANCELED',
  CHALLENGE_NOT_FOUND: 'CHALLENGES.CHALLENGE_NOT_FOUND',
  PARTICIPATION_NOT_FOUND: 'CHALLENGES.PARTICIPATION_NOT_FOUND',
  PROGRESS_CANNOT_DECREASE: 'CHALLENGES.PROGRESS_CANNOT_DECREASE',
  INVALID_INVITE: 'CHALLENGES.INVALID_INVITE',
  INVALID_CREATOR_ID: 'CHALLENGES.INVALID_CREATOR_ID',
  NOT_AUTHORIZED: 'CHALLENGES.NOT_AUTHORIZED',
  CHALLENGE_DOES_NOT_REQUIRE_INVITE: 'CHALLENGES.CHALLENGE_DOES_NOT_REQUIRE_INVITE',
} as const;

export type ChallengeErrorCode = (typeof ChallengeErrorCodes)[keyof typeof ChallengeErrorCodes];
